language: php

php:
  - 7.0
  - 7.1

sudo: false

install:
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - bash <(curl -s https://codecov.io/bash)
